### ISSUE TITLE
image requirements 

### ISSUE THREAD

**Issue by skim245** [LieberInstitute/VistoSeg#11]
Dear authors, thank you for developing VistoSeg. 
I have a question about the input image requirements to run this tool.
Do we need the original image? or can we use the image from "SpaceRanger" in tissue_hires_image.png format? 
if we could used the preprocessed (i.e. cropped images) can you guide me on steps to do so? 
thank you in advance!

**Comment by madhavitippani** [comment]
Hello,

Thanks for reaching out. We need the original image to process it through VistoSeg. 
You can find the detailed steps here http://research.libd.org/VistoSeg/
