### ISSUE TITLE
Error while running the corrected countSpots_centroid.m code

### ISSUE THREAD

**Issue by Ukaipa9** [LieberInstitute/VistoSeg#19]
{Error: File:
/dcs04/lieber/marmaypag/spatialDLPFC_SCZ_LIBD4100/code/vistoseg/lib_updated/countSpots_centroid.m
Line: 36 Column: 18
Functions cannot be indexed using {} or . indexing.

Error in countNuclei (line 30)
       [count,prop,countC] = countSpots_centroid(BW, R, tbl, posPath);
}

**Comment by madhavitippani** [comment]
it's due to a MATLAB version mismatch, if using MATLAB 2021 or earlier refer to this commit https://github.com/LieberInstitute/VistoSeg/commit/ec55bfde52ca89a0a78cfd4defa648be20aa81d2
